// fUNCAO COMUM NO JAVASSCRIPT

function somar(a,b) {
    return a + b
}

function subtrair(a,b) {
    return a - b
}

function divisao(a,b) {
    return a/b
}

function multiplicar(a,b) {
    return a * b

}

const soma = somar(2,3)
const subtracao = subtrair(2,3)
const divisao = dividir(2,3)
const multiplicar = multiplicar(2,3)

console.log("Soma:", soma)
console.log("subtração:", subtracao)
console.log(`Divisão: ${divisao}`)
console.log(`Multiplica]ap: ${multiplicar}`)